server:
  port: 3333
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  
      routes:
      - id: one
        uri: lb://WELCOME-API
        predicates:
          - Path=/msg
      
      - id: two
        uri: lb://GREET-API 
        predicates:
          - Path=/greet     
  main:
    web-application-type: reactive
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ 