server:
  port: 9090
  
spring:
  application:
    name: BMS-API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: BOOKINGS-SERVICE
        uri: lb://BOOKINGS-SERVICE
        predicates:
          - Path=/booking/**
        filters:
        - AuthenticationFilter  
          
      - id: FOOD-SERVICE
        uri: lb://FOOD-SERVICE
        predicates:
          - Path=/foods/**
        filters:
          - AuthenticationFilter
        
               
      - id: MOVIE-SERVICE
        uri: lb://MOVIE-SERVICE
        predicates:
          - Path=/movies/** 
        filters:
          - AuthenticationFilter          
          

      - id: PAYMENT-SERVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payments/** 
        filters:
          - AuthenticationFilter
                  

      - id: SHOWTIME-SERVICE
        uri: lb://SHOWTIME-SERVICE
        predicates:
          - Path=/showTime/**
        filters:
          - AuthenticationFilter
                  
          
      - id: THEATER-SERVICE
        uri: lb://THEATER-SERVICE
        predicates:
          - Path=/theaters/**
        filters:
          - AuthenticationFilter
                   
          
      - id: TICKET-SERVICE
        uri: lb://TICKET-SERVICE
        predicates:
          - Path=/tickets/** 
        filters:
          - AuthenticationFilter
                    
          
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/users/**
        filters:
          - AuthenticationFilter          
                                                                   

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka