server:
  port: 8085
  
spring:
  application:
    name: CONFIG_SERVER  
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krkhengte/Microservices-Application-Configuration
          clone-on-start: true
          