server:
  port: 9094
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmyshow_showtimeService
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver  

  application:
    name: SHOWTIME-SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dilect: org.hibernate.dialect.MySQL8Dialect  
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




        
        